### ISSUE TITLE
Crates.io E-mentor issues

### ISSUE THREAD

**Issue by carols10cents** [cmr/this-week-in-rust#1063]
Hi! In Nov and Dec, I'm concentrating on doing crates.io maintenance that enables more contributors. One of those tasks is writing up more contribution instructions, and I'm tagging those issues with E-mentor; there's 7 right now but I'm working on adding more: https://github.com/rust-lang/crates.io/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AE-mentor

I'd love to have this publicized in TWiR ❤️ Not sure if you'd like to list all the issues or just a link to that search, either would be fine with me!

**Comment by nasa42** [comment]
I noticed 10 issues so they would be too many to list individually, so I've linked directly to the list. I'll publish it in multiple subsequent TWiR issues for more publicity. :+1:

**Comment by carols10cents** [comment]
Sounds great! Thank you so much ❤️
