### ISSUE TITLE
Links to discussion?

### ISSUE THREAD

**Issue by triptec** [cmr/this-week-in-rust#1088]
I was wondering if there’s a reason why there’s no links to hackernews or reddit discussions next to the links to the blog posts?

If I take myself as a example I used to be a casual/more than casual rust user but since going on parental leave I haven’t touched my laptop for months. So I’m basically only using my phone and that makes it so much more time consuming to copy url and search for it on other platforms that I just don’t. Having links in the newsletter and the site would make it so much simpler for me at least.

**Comment by nasa42** [comment]
We did briefly have reddit links however they were removed. You can find more information here: https://github.com/cmr/this-week-in-rust/issues/709.
