### ISSUE TITLE
Link request to training interest form

### ISSUE THREAD

**Issue by carols10cents** [cmr/this-week-in-rust#1117]
Hi! I know you do look at Reddit for links, so this is probably already in your list of links to include, but I wanted to make sure. I also wanted to mention that if this is too advertising-ey for TWiR, I totally understand.

Jake Goulding and I are thinking about offering training in Pittsburgh sometime in May and have a form where we're gathering interest: https://forms.gle/UWsj9qbGJFBc2poV8

Thanks!

**Comment by nasa42** [comment]
I'll get it included in CfP section in this weeks' issue, thanks for sharing. :-)
