### ISSUE TITLE
Crate of the Week 39

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#127]
The Crate of the Week is BurntSushi's [quickcheck](https://github.com/BurntSushi/quickcheck). Out of [all quickcheck implementations](https://en.wikipedia.org/wiki/Quickcheck), this is probably one of the more impressive ones. Thanks to DanielKeep, who had [this](https://users.rust-lang.org/t/crate-of-the-week/2704/40) to say:

> It helps write property-based tests: you define some property and how to test it, and quickcheck feeds your test random inputs as it tries to narrow down the ranges within which the property fails to hold. Handy when the set of possible test cases is very large.

I'd like to add an appeal to all supporters of "repeatable tests". Don't let the worthy goal of repeatability override the worthier goal of actually finding bugs. Your deterministic tests usually cannot even make a dent in the vast space of possible inputs. With a bit of randomness thrown in, you can greatly improve you chances and thus make your tests more valuable. Also with quickcheck, you get to see a *minimized* input that makes your test fail, which you can then turn into a repeatable test easily.

**Comment by nasa42** [comment]
Been waiting for this, thanks!

**Comment by llogiq** [comment]
My pleasure, and sorry for the delay.
