### ISSUE TITLE
Crate of the Week 40

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#129]
This time I resolved not to nag Rustdom with calls for nominations, and we only got two crates and no votes. Great! I guess this means I can write about whatever I want. :smile:

So today I'll write about [rust-itertools](https://crates.io/crates/itertools). Because iterators in Rust are awesome, and this crates makes them even awesome-r. If you want to do something with iterators that seems to be slightly impossible using the `std` APIs, chances are `itertools` already implements a way that is both fast and elegant. Knowing your itertools APIs will level up your Rust-fu.

For a (very small and simple) example, haven't you wished to zip two iterators, but don't stop iteration after the shorter iterator has run out? With `itertools` you can just say `x.zip_longest(y)` and get an iterator of `EitherOrBoth<X, Y>`.

**Comment by nasa42** [comment]
Thanks!
(renamed "rust-itertools" to "Itertools", as that is the name mentioned on https://github.com/bluss/rust-itertools).

**Comment by nasa42** [comment]
@llogiq I think 40 is wrong, as we'll be releasing issue 99 this week. :-)

**Comment by llogiq** [comment]
Oh, l appear to be behind the times... Thanks for the corrections, @nasa42.
