### ISSUE TITLE
restore previous style

### ISSUE THREAD

**Issue by flying-sheep** [cmr/this-week-in-rust#132]
the big font, no nonsense style was much less cluttered.

i think [this](http://blog.servo.org/2015/10/05/twis-36/) looks so much better than [this](http://this-week-in-rust.org/blog/2015/10/05/this-week-in-rust-99/)

**Comment by nasa42** [comment]
You might like the changes in https://github.com/cmr/this-week-in-rust/commit/e1e8c352c787f5677a3f8e501d82bb9877ab2da6
Also, TWiR never had the same theme as Servo blog.

**Comment by flying-sheep** [comment]
thanks, this is indeed much better!
