### ISSUE TITLE
TWIR 100 Crate of the Week

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#135]
The Crate of this week is [Conrod](https://crates.io/crates/conrod), a simple to use intermediate-mode GUI library written in pure Rust. Thanks to [7zf](https://www.reddit.com/user/7zf).

Conrod forgos the traditional "wrap the default GUI for each operating system/desktop environment" approach and uses OpenGL to present a simple, but color- as well as powerful GUI in its own style. There are a good number of widgets implemented already, and writing GUI code with conrod is a breeze thanks to the very streamlined interface.

**Comment by nasa42** [comment]
Thanks @llogiq!
Also your blog post is the opener link in issue 100. :-)
http://this-week-in-rust.org/blog/2015/10/12/this-week-in-rust-100/

**Comment by llogiq** [comment]
I'm honored. :smile:
