### ISSUE TITLE
TWIR 101 CotW

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#137]
This week's Crate of the Week is  [glium](https://github.com/tomaka/glium) a safe Rust wrapper for OpenGL. Thanks to [DroidLogician](https://users.rust-lang.org/users/DroidLogician) for the suggestion.

OpenGL is a time-honored standard, which also means its API has seen enough growth to make it look like you might find Sleeping Beauty if you look deep enough. Also it was created when multicore wasn't exactly on the radar, so many things are not thread safe. Caveat error! Glium pre-verifies whatever it can to make errors either impossible at compile time or panic before it can crash (so you at least get a helpful message instead of random garbage). It caches the context, manages your buffers using Rust's standard RAII idiom and by this brings some much-needed sanity to OpenGL programming.

**Comment by nasa42** [comment]
Now published. Thanks @llogiq!

**Comment by llogiq** [comment]
My pleasure.
