### ISSUE TITLE
community notes 22.10.2015

### ISSUE THREAD

**Issue by skade** [cmr/this-week-in-rust#138]
* There's a Rust workshop with Women Who Code on the November 2nd at Codemotion Berlin: http://berlin2015.codemotionworld.com/news/women-who-code-workshop-introduction-to-rust/
You need to sign up. There's a talk on the next day.
* We sent in an application for a devroom at FOSDEM 2016, but it was rejected. It is still possible to submit talks to the accepted devrooms, though!
* We are currently applying to be present at a couple of other events.
* There are plans for an assembly at [32C3](https://events.ccc.de/category/congress/32c3/), the german hacker congress.

**Comment by brson** [comment]
@nasa42 I've added the codemotion event to the calendar. Please include it in twir. The other bullets I'm going to put into this week's subteam reports.

**Comment by brson** [comment]
cc https://github.com/rust-lang/subteams/pull/16

**Comment by skade** [comment]
Just want to clarify that the codemotion workshop is actually a result of community-team work :). So it kind of fits in both.
