### ISSUE TITLE
Dead link to contributing

### ISSUE THREAD

**Issue by dato** [cmr/this-week-in-rust#140]
The newsletter link [We love contributions][1] is a dead link. It points to:

<https://github.com/rust-lang/rust/wiki/Note-guide-for-new-contributors>

which doesn’t seem to exist any more.

I tried to find out where the wiki lives now, but I was unable to.

Thanks!

[1]: https://github.com/rust-lang/rust/wiki/Note-guide-for-new-contributors

**Comment by nasa42** [comment]
Fixed to https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md in latest issue.
