### ISSUE TITLE
TWIR 103 Crate of the Week

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#144]
Thanks go to reddit user [notriddle](https://www.reddit.com/user/notriddle) for this week's Crate of the Week, which is Huon W.'s [alias](https://crates.io/crates/alias), which allows *mutably aliasing* values – which seems to actually be safe, somewhat surprisingly. Honestly, I'm a bit shocked about it myself.

**Comment by nasa42** [comment]
Oh I just got both Crate and Quote of the Week here :-)

**Comment by llogiq** [comment]
:smiley:
