### ISSUE TITLE
This week in Rust 106's CotW

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#147]
This week's Crate of the Week is [nom](https://crates.io/crates/nom), a library of fast zero-copy parser combinators, which has already been used to create safe, high-performance parsers for a number of formats both binary and textual. nom just reached version 1.0, too, so congratulations for both the major version and the CotW status are in order! :smile: Thanks to reddit user gbersac for the [nom-ination](https://www.reddit.com/r/rust/comments/3t10f3/nom_just_reached_10_cleaner_parsers_more_generic/cx2or2m).

**Comment by nasa42** [comment]
pun-tastic! :wink:

**Comment by llogiq** [comment]
[Not my pun](https://www.reddit.com/r/rust/comments/3t10f3/nom_just_reached_10_cleaner_parsers_more_generic/cx4xroq) – credit where credit is due.
