### ISSUE TITLE
TWIR 118's COTW + interesting PRs

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#170]
This week's crate of the week is [rayon](https://crates.io/crates/rayon), which gives us `par_iter()`/`par_iter_mut()` functions that use an internal thread pool to easily parallelize data-parallel operations. There's also `rayon::join(|| .., || ..)` for Fork-Join-style tasks. Apart from the ease of use, it also performs very well, comparable to hand-optimized code. Thanks to [LilianMoraru](https://users.rust-lang.org/users/LilianMoraru/activity) for the suggestion.

Also here are links to the (IMHO) interesting PRs merged:
https://github.com/rust-lang/rust/pull/31551
https://github.com/rust-lang/rust/pull/31545
https://github.com/rust-lang/rust/pull/31468
https://github.com/rust-lang/rust/pull/31442
https://github.com/rust-lang/rust/pull/31425 (Yay! MIR Compiler plugins!)
https://github.com/rust-lang/rust/pull/31651 (eddyb fixes an old bug)
https://github.com/rust-lang/rust/pull/31562 (some more methods for lints. Full disclosure: From me – feel free to skip if you deem it unimportant)
https://github.com/rust-lang/rust/pull/31630
https://github.com/rust-lang/rust/pull/31629 (some love for i585 users)

And a big refactoring that actually broke some things
https://github.com/rust-lang/rust/pulls?q=is%3Apr+org%3Arust-lang+is%3Amerged+merged%3A2016-02-08..2016-02-15+[breaking-batch]

**Comment by nasa42** [comment]
Thanks @llogiq!
