### ISSUE TITLE
2016-06-29-this-week-in-rust.md should be 2016-02-29-this-week-in-rust.md

### ISSUE THREAD

**Issue by hobofan** [cmr/this-week-in-rust#186]
The filename of the markdown file for TWiR 120 has the wrong date in it.

Is that something that can be easily fixed or does that filename affect some links that would be broken by changing it?

**Comment by nasa42** [comment]
Links shared across Twitter, Reddit, email etc. will be broken.

**Comment by hobofan** [comment]
I looked some more into it and it the link on reddit uses https://this-week-in-rust.org/blog/2016/02/29/this-week-in-rust-120/, as do the rss feed and the email.

It looks like the link might only be influenced by the date in the header of the file.

**Comment by nasa42** [comment]
Yes, in that case, we can safely change the file name. I'll do so.
