### ISSUE TITLE
IPv6 connection problems

### ISSUE THREAD

**Issue by klemens** [cmr/this-week-in-rust#212]
`this-week-in-rust.org` does have a AAAA record that points to `2600:3c03::f03c:91ff:fee4:cb69`. That IP however does not respond to any packets (not even with `destination unreachable`).
This results in eg. `wget` waiting the full tcp connect timeout before falling back to IPv4.

I also noticed that the feeds include all past issues, which currently results in a 1,5 MiB atom.xml. Is this intended? The number of entries [can be limited][1] through `FEED_MAX_ITEMS`.

[1]: http://docs.getpelican.com/en/3.6.3/settings.html#feed-settings

**Comment by cmr** [comment]
That isn't intended, I'll change it to only contain the last 4 items. I'll remove that record for now. It's at the very least out of date, and the IPv6 configuration seems broken...

**Comment by cmr** [comment]
https://github.com/cmr/this-week-in-rust/commit/f089bff9e6e4dd65f3ed6f19f723d6498c75c2b3
