### ISSUE TITLE
'the team' link under Final Comment Period doesn't work

### ISSUE THREAD

**Issue by reddraggone9** [cmr/this-week-in-rust#218]
The [link (src)] to the team is https://rust-lang.org/team.html. This doesn't work for me. According to nmap, that server isn't listening for https requests:
```sh
$ nmap rust-lang.org
Starting Nmap 6.40 ( http://nmap.org ) at 2016-05-12 17:47 CDT
Nmap scan report for rust-lang.org (192.241.171.49)
Host is up (0.059s latency).
rDNS record for 192.241.171.49: fwd01.do.easydns.com
Not shown: 992 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   open     http
111/tcp  open     rpcbind
135/tcp  filtered msrpc
139/tcp  filtered netbios-ssn
445/tcp  filtered microsoft-ds
3306/tcp open     mysql
3918/tcp open     pktcablemmcops
```

Changing the link [to http] results in a redirect to https://www.rust-lang.org/team.html, which does work. The www subdomain strikes again!

[to http]: http://rust-lang.org/team.html
[link (src)]: https://github.com/cmr/this-week-in-rust/blame/master/content/2016-05-09-this-week-in-rust.md#L108

**Comment by brson** [comment]
Thanks for the report. Fixed in next week's draft.
