### ISSUE TITLE
No draft/ directory

### ISSUE THREAD

**Issue by Yamakaky** [cmr/this-week-in-rust#223]
The README mentions a `drafts/` directory for the next issue, but I can't find it?
It's for bindgen 0.17.

**Comment by nasa42** [comment]
There is one now. :-)

**Comment by kraai** [comment]
@nasa42, I can't find the drafts directory either.  I've checked both the latest version and the version from May 27, 6121852a12b378a7c70d11609700848a8dfbf5ec.

**Comment by nasa42** [comment]
Sorry, forgot again. There is one now.

**Comment by nczhu** [comment]
Hey sry, I couldn't find a drafts folder, so just made a PR directly in `contents` folder. Hope that works! thanks
