### ISSUE TITLE
Support emoji

### ISSUE THREAD

**Issue by nasa42** [cmr/this-week-in-rust#241]
@llogiq put a `:smile:` emoji in PR https://github.com/cmr/this-week-in-rust/pull/240 and it was printed verbatim. We should add support for emoji (probably replacing `:smile:` with respective Unicode character by injecting some filter in Markdown -> HTML pipeline?).

**Comment by AndiDog** [comment]
Why not just use Unicode directly? Windows 10 and macOS have emoji on-screen keyboards built-in, and probably other OSes, too. The glyphs can also be copied from the web, WhatsApp Web, or other places. I believe replacing meta strings like `:smile:` might be overkill nowadays that smileys are all around 🤓🎉

**Comment by llogiq** [comment]
That's what we ended up doing, but it's more tedious than needed.

**Comment by nasa42** [comment]
We are already printing the Unicode character for emojis in our issues.
