### ISSUE TITLE
Blog post missing

### ISSUE THREAD

**Issue by llogiq** [cmr/this-week-in-rust#311]
I published [From tweet to Rust Feature](https://llogiq.github.io/2016/09/14/feature.html) this week, perhaps it fits well with our general theme? I'd PR, but the master doesn't seem to be current.

@nasa42

**Comment by nasa42** [comment]
I'd suggest to PR for next week's draft as newsletters are already sent. Sorry.

**Comment by nasa42** [comment]
I'd suggest to PR for next week's draft as newsletters are already sent. Sorry.

**Comment by llogiq** [comment]
It's all good. I'll close this issue with the PR then.
