### ISSUE TITLE
Add rust-unofficial/patterns to Call for Participation

### ISSUE THREAD

**Issue by lfairy** [cmr/this-week-in-rust#313]
[rust-unofficial/patterns](https://github.com/rust-unofficial/patterns) aims to be a catalog of Rust design patterns.

@cbreeden and I have been recruited as editors for this project, and would love to have more people involved. We need help on writing new articles, and giving feedback on existing submissions.

Can you add this project to the next Call for Participation please?

**Comment by nasa42** [comment]
Added to current issue (yet to publish). Maybe you should also advertise _collaborators wanted_ in your README with instructions on how to contact project maintainers for those who are interested.
