### ISSUE TITLE
Multiple Updates from Rust Core links wrong in 149

### ISSUE THREAD

**Issue by b-ambrus** [cmr/this-week-in-rust#319]
In the This Week in Rust 149 document at "https://this-week-in-rust.org/blog/2016/09/27/this-week-in-rust-149/", in the section "Updates from Rust Core", some of the updates mentioned are a link to the wrong target.  

 - "TypedArena now allocates lazily" should link to https://github.com/rust-lang/rust/pull/36592
 - "RBML is gone" should link to https://github.com/rust-lang/rust/pull/36551

The current link targets are definitely wrong, because they are equal to the target of a previous link, but I'm not completely certain I identified the correct targets here, so please check that.

**Comment by nasa42** [comment]
Fixed now, thanks!
