### ISSUE TITLE
How many people subscribe to the email newsletter?

### ISSUE THREAD

**Issue by carols10cents** [cmr/this-week-in-rust#327]
If this is not something you'd like to divulge, or not something that is possible to find out, no worries. I've been asked for some numbers around how many people use Rust, and that is hard to get, so I'm looking for numbers that would be easier to get that could be proxies :)

**Comment by nasa42** [comment]
2458 at present. Here is the chart from MailChimp.

![Uploading Screenshot from 2016-10-07 17-43-34.png…]()

**Comment by nasa42** [comment]
2458 at present. Here is the chart from MailChimp.

![screenshot from 2016-10-07 17-43-34](https://cloud.githubusercontent.com/assets/233999/19189564/4feda628-8cb6-11e6-82a5-5fd71d4415da.png)

**Comment by carols10cents** [comment]
Awesome, this is great!! Thank you so much!! ❤️
