### ISSUE TITLE
Change content type for rss and atom feed

### ISSUE THREAD

**Issue by sergeysova** [cmr/this-week-in-rust#375]
Change nginx server settings on your settings:

Set `Content-Type` header to `application/rss+xml` for https://this-week-in-rust.org/rss.xml.    
And `application/atom+xml` for /atom.xml. ([Why?](https://msdn.microsoft.com/en-us/library/dd541377.aspx))

IFTTT do not parse this link as XML-RSS

Now:

![image](https://cloud.githubusercontent.com/assets/5620073/22013086/479fa0b0-dca8-11e6-9585-17d3bbe83378.png)

**Comment by skade** [comment]
Relevant link: https://help.github.com/articles/mime-types-on-github-pages/

There seem to be mime-db definitions for atom+xml, rss+xml, but I didn't quite grok how to trigger them.

**Comment by nasa42** [comment]
@cmr hosts TWiR on a Linode server. Assigning this issue to him as this requires changes in server config.

**Comment by nasa42** [comment]
We now host TWiR on GItHub Pages. However, to send with `Content-Type` `application/rss+xml`, URL will need to be changed to https://this-week-in-rust.org/rss.rss which will be a major breaking change. I guess it's too late to change now.

GitHub Pages uses following config to set `Content-Type`.

https://github.com/jshttp/mime-db/blob/4db92114124a76a38bf29b7d572d4c7da33a1261/db.json#L1212-L1215
