### ISSUE TITLE
ISO dates

### ISSUE THREAD

**Issue by bestouff** [cmr/this-week-in-rust#390]
Would it be possible to use [ISO dates](https://xkcd.com/1179/) in the "Upcoming Events" section ?

**Comment by nasa42** [comment]
Affirmative.

**Comment by nasa42** [comment]
While I did not change the dates to `YYYY-MM-DD` format which seems quite redundant given the scope, I did change it to `Feb 14` to avoid ambiguity between `dd/mm` and `mm/dd`.
