### ISSUE TITLE
FCPs should be obtained from http://rusty-dash.com/fcp

### ISSUE THREAD

**Issue by gnzlbg** [cmr/this-week-in-rust#410]
Currently it seems that FCPs announcements are only obtained from the RFC repo, but this is woefully incomplete, since a lot of them are in other repos that are part of the rust-lang or (like rust-lang/rust). 

The correct place to obtain information and track FCPs is http://rusty-dash.com/fcp .

**Comment by nasa42** [comment]
It seems like http://rusty-dash.com/fcp lists RFCs that _would go to_ FCP after team reaches a consensus, and not RFCs that are _already in_ FCP. In TWiR, we list RFCs that are already in FCP.
I also looked at https://github.com/rust-lang/rust/labels/final-comment-period (rust repo) and all issues here are _tracking-issue_ for already accepted RFCs.
So, I think it currently makes sense to stick to https://github.com/rust-lang/rfcs/labels/final-comment-period (rfc repo).

**Comment by gnzlbg** [comment]
I just posted this because the lasts TWiR all missed the final comment period on `cfg_target_feature`, which is listed on rusty-dash, but not here, so... something must be odd.

**Comment by nasa42** [comment]
It would probably be too much information to include if TWiR also listed FCPs from other rust-lang org repositories.

If anyone is interested, it is easy to find the list at [this page](https://github.com/search?q=label%3Afinal-comment-period+org%3Arust-lang+is%3Aopen).

**Comment by nasa42** [comment]
I've changed my stance on this, and starting this week, FCPs from rust-lang/rust repo are also included.
