### ISSUE TITLE
issue 177 gitlab contributor

### ISSUE THREAD

**Issue by fbstj** [cmr/this-week-in-rust#425]
issue [177](https://this-week-in-rust.org/blog/2017/04/11/this-week-in-rust-177/) had a new contributor called 'GitLab', is that the company gitlab or just some weirdness?

**Comment by nasa42** [comment]
This list in TWiR is auto-generated. That name comes from this commit - https://github.com/rust-lang/rust/commit/56902fbe71b9b0a9b327972412fca085a8770e61 (PR: https://github.com/rust-lang/rust/pull/40479).
That could be a mistake from commit author's part. But I'd like to stick with names that go in Git unless it's more serious.

**Comment by sezaru** [comment]
I'm so sorry about this, the computer I used to do the changes had that weird name from when I was playing with a local gitlab installation.

I didn't replied sooner because I'm super busy right now moving to a new house.
