### ISSUE TITLE
next quote of the week

### ISSUE THREAD

**Issue by Geal** [cmr/this-week-in-rust#438]
I'm nominating this tweet https://twitter.com/badboy_/status/861699384840507392

**Comment by Geal** [comment]
(in the context of exploring rustc's source to understand how it works without documentation)

**Comment by jeanm** [comment]
I quite liked [this reddit comment by /u/kibwen](https://www.reddit.com/r/rust/comments/69zca2/what_does_rust_mean/dhb20yb/)

**Comment by Geal** [comment]
That one is great too!

**Comment by nasa42** [comment]
For this week, we've decided to go with [kibwen's comment](https://www.reddit.com/r/rust/comments/69zca2/what_does_rust_mean/dhb20yb/). :slightly_smiling_face: 
Thanks for suggestions!
