### ISSUE TITLE
Rust Belt Rust CFP open now

### ISSUE THREAD

**Issue by carols10cents** [cmr/this-week-in-rust#479]
Hi! Not sure whether you'd like this under news, events, or somewhere else, but I'd love to get a link to Rust Belt Rust's CFP in this week: http://cfp.rust-belt-rust.com/ Deadline is Mon Aug 7 :) Thanks!

**Comment by nasa42** [comment]
I'll mention it under "Call for Participation" and then duplicate to "Events"?

**Comment by carols10cents** [comment]
Sounds great! Thank you!!!
