### ISSUE TITLE
DKIM is not properly set up

### ISSUE THREAD

**Issue by ishitatsuyuki** [cmr/this-week-in-rust#549]
The key is from a MailChimp domain, not rust-lang.org. I recommend to properly set it up as ProtonMail warns it (probably a bug though).

```
Dkim-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=k1; d=mail145.atl21.rsgsv.net;
 h=Subject:From:Reply-To:To:Date:Message-ID:List-ID:List-Unsubscribe:Sender:
 Content-Type:MIME-Version; i=twir=3Drust-lang.org@mail145.atl21.rsgsv.net;
```

**Comment by nasa42** [comment]
It is unlikely that I can get `rust-lang.org` domain to be authenticated for TWiR's MailChimp account.
Unless this becomes a major issue, I'd say that current situation (MailChimp's default authentication) is an acceptable compromise for using `rust-lang.org` domain for TWiR's emails.
