### ISSUE TITLE
Blog series about Futures

### ISSUE THREAD

**Issue by msehnout** [cmr/this-week-in-rust#550]
Hi, I'm not sure if this is the right place to propose a new articles for inclusion, but I found this series of blog posts somewhere on Twitter and I think it would be worth sharing:
https://dev.to/mindflavor/rust-futures-an-uneducated-short-and-hopefully-not-boring-tutorial---part-1-3k3

**Comment by nasa42** [comment]
It will be included in this week's issue. Thanks!
