### ISSUE TITLE
Berlin Hack & Learn missing

### ISSUE THREAD

**Issue by hobofan** [cmr/this-week-in-rust#602]
The [Berlin Rust Hack & Learn](http://www.meetup.com/opentechschool-berlin/) is missing from the [current issue](https://this-week-in-rust.org/blog/2018/02/13/this-week-in-rust-221/). It seems to have vanished from the community calendar completely, including all past event.

@skade, @johannhof

**Comment by nasa42** [comment]
We've no issues adding them to TWiR but as you mentioned, they seem to have disappeared from the calendar.
Please get in touch with Community team to add these events back to calendar, and they should reappear in TWiR too.

**Comment by johannhof** [comment]
I added it back to the calendar, thanks for alerting me :)
