### ISSUE TITLE
An invitation to join the Rust Community Content sub-team.

### ISSUE THREAD

**Issue by booyaa** [cmr/this-week-in-rust#607]
Hi!

The community team has started a new sub team for all things Rust content related. We're inviting people to join the team so we can share useful information and projects that the Content team are currently work on.

It was suggested that we invite the TWIR team to join.

We meet on alternating Tuesdays 5:30-6pm UTC to the main Community meeting. More details can be found in this week's [agenda](https://github.com/rust-community/content-team/issues/7).

Cheers,

Mark (team lead)

**Comment by nasa42** [comment]
Thanks @booyaa! I'll be present at today's meeting.
