### ISSUE TITLE
Call for participation: rustc-guide

### ISSUE THREAD

**Issue by mark-i-m** [cmr/this-week-in-rust#608]
The rustc guide is more of a writing project than a programming project, but there are a bunch of things that need doing: https://github.com/rust-lang-nursery/rustc-guide/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

The difficulty ranges from "copy the contents of the rustc READMEs" or "proofreading" to "write about the dark bowls of X in rustc". Prior knowledge of compiler internals is _not_ required.

The goal is for this replace the READMEs in the rust-lang/rust src tree and become the official guide to rustc contribution (eventually).

**Comment by nasa42** [comment]
I'll include it in today's issue. Thanks.
