### ISSUE TITLE
Where to unsubscribe?

### ISSUE THREAD

**Issue by towry** [cmr/this-week-in-rust#619]
I can not found the unsubscribe link in the email.

<img width="478" alt="2018-03-27 8 22 03" src="https://user-images.githubusercontent.com/8279858/37939876-f6aedee6-3197-11e8-9669-f2a24001ca00.png">

**Comment by nasa42** [comment]
It looks like the last line is not visible in your screenshot because I can see the "Unsubscribe" link in Gmail. Which email client are you using?

![screenshot from 2018-03-27 22-18-04](https://user-images.githubusercontent.com/233999/37982039-f36eab92-320c-11e8-9714-ed189931f40c.png)

**Comment by towry** [comment]
Outlook, I do not use that email often, and I want to stop receiving subscription emails.
