### ISSUE TITLE
Highlight issues in the homepage

### ISSUE THREAD

**Issue by flavius** [cmr/this-week-in-rust#62]
... Either highlight, or better yet, tag the issues which correspond to new releases of the compiler, like `rustc-1.0`, `rustc-1.1`, `cargo-1.0`, so that we can see which changes came in relative to which issue of "this week in rust", and to better see what falls in-between.

**Comment by nasa42** [comment]
Since this issue was filed, the design has substantially changed. Closing.
Please create a new issue if you'd like to suggest changes in our new design.
