### ISSUE TITLE
Telegram channel

### ISSUE THREAD

**Issue by berkus** [cmr/this-week-in-rust#623]
Hey, is https://t.me/this_week_in_rust your channel?

It's been spamming all the same articles list for 5th or 6th time in a row in the past couple weeks, and there's no contact info in the about.

If you're not the owner, feel free to close this. If you know the owner, please forward this report to them.

Thanks!

**Comment by nasa42** [comment]
AFAIK, we do not operate any Telegram channels. In fact, this is the first time I'm hearing about it.

**Comment by berkus** [comment]
Interesting, I'm wondering where it takes the list of stuff to post, pity it's impossible to find the maintainer.

**Comment by nasa42** [comment]
There doesn't seem to be much that we can do about this, so I'd close this issue for now. Please reopen this issue if you feel otherwise.
I'd also advise to unsubscribe from the channel if you don't it useful.

**Comment by berkus** [comment]
Hi,

I located the maintainer of the channel, so all is good now, thanks for taking time to answer :)

**Comment by nasa42** [comment]
Hi @berkus, could you please let me know who is the owner? You can also email me privately at the email address mentioned on my [GitHub profile](https://github.com/nasa42).

**Comment by berkus** [comment]
I've asked the guy to contact you.
