### ISSUE TITLE
Link to page in RSS feed is wrong

### ISSUE THREAD

**Issue by Jesse-Millwood** [cmr/this-week-in-rust#631]
When I click on the link to the page from my RSS feed it takes me to: tag:this-week-in-rust.org,2018-04-17:blog/2018/04/17/this-week-in-rust-230/ 
instead of : https://this-week-in-rust.org/blog/2018/04/17/this-week-in-rust-230/

I am subscribing to the RSS feed through Firefox's Brief plugin. I only bring this up because I don't have this problem with any other feeds, so I thought I'd let you know.

**Comment by nasa42** [comment]
Sorry for a late reply. Is this still an issue?

**Comment by Jesse-Millwood** [comment]
Looks good now
