### ISSUE TITLE
New label on rust-lang/rust PRs: S-waiting-on-bikeshed

### ISSUE THREAD

**Issue by pietroalbini** [cmr/this-week-in-rust#636]
There is a new status label in the rust-lang/rust repo: [S-waiting-on-bikeshed](https://github.com/rust-lang/rust/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+label%3AS-waiting-on-bikeshed). All the PRs waiting on bikeshedding will be labelled with it, so it might be a good idea to add them to TWIR like for FCPs and RFCs to get more discussion?

cc @shepmaster

**Comment by nasa42** [comment]
Thanks for getting this to our attention.
IMHO, TWiR is already quite long and I don't feel that adding a new section for `S-waiting-on-bikeshed` will be helpful for wider Rust community.

Additionally, this label seems to be used sparingly and applied to only one issue so far.
