### ISSUE TITLE
#May 22's 235's "Validating UTF-8 strings..." is C, no Rust

### ISSUE THREAD

**Issue by skierpage** [cmr/this-week-in-rust#643]
https://lemire.me/blog/2018/05/16/validating-utf-8-strings-using-as-little-as-0-7-cycles-per-byte/ is really cool, but I followed the links and all seems C code. Is it in the list because it's a generally interesting faster algorithm?

Thanks for TWiR!

**Comment by nasa42** [comment]
Oops, it indeed is! I've removed the article! Thanks for pointing this out.
