### ISSUE TITLE
Group events in "Upcoming Events" section by location

### ISSUE THREAD

**Issue by siddharthasahu** [cmr/this-week-in-rust#653]
Hi!

In reading through the meetups/events listed in the "Upcoming Events" section of TWiR, my main goal is to find something that is happening close to my location, rather than when.

How about grouping the events by location first? Grouping the events by country/continent would help quickly pinpoint events I can possibly attend.

Thanks!

**Comment by nasa42** [comment]
Starting today's issue, events will be grouped by continent. Thanks for the suggestion!
