### ISSUE TITLE
Make "upcoming events" tabular data

### ISSUE THREAD

**Issue by xliiv** [cmr/this-week-in-rust#654]
I'd nice if "upcoming events" were in table.

Date|City|Country|Title
------|-----|----------|------
01.01.0001|London|England|Rust Meetup

**Comment by nasa42** [comment]
Introducing tables in the current UI would be quite a significant change and we'll need to test the newsletter layout in various email clients.

Also, as mentioned in https://github.com/cmr/this-week-in-rust/issues/653, starting today's issue, events will be grouped by continent. Hopefully, that will help you in quicker scanning for relevant events.
