### ISSUE TITLE
In the News & Blog Posts section would it be possible to get links to any discussion (if there is any) on reddit, hackernews etc? 

### ISSUE THREAD

**Issue by hgallagher1993** [cmr/this-week-in-rust#668]

**Comment by nasa42** [comment]
Starting next week, we plan to add reddit links as an experiment and watch for community's feedback. Thanks for the idea!

(PS: Also [discussed here](https://www.reddit.com/r/rust/comments/97czdf/this_week_in_rust_247/e47977d/)).
