### ISSUE TITLE
Is the website down now?

### ISSUE THREAD

**Issue by mzji** [cmr/this-week-in-rust#679]
At 2018/07/19 04:24 UTC, the website looks down.

**Comment by matthiasbeyer** [comment]
Same here.

**Comment by nasa42** [comment]
There seem to be some server issue and I've pinged @cmr who maintains the server.
Meanwhile, the site is up at a new address https://this-week-in-rust.github.io/

**Comment by cmr** [comment]
Not really sure what happened there... seems the network interface went down for some reason? The logs don't tell me anything. Anyway, it's back up now.
