### ISSUE TITLE
Links to api.github.com

### ISSUE THREAD

**Issue by vi** [cmr/this-week-in-rust#698]
https://this-week-in-rust.org/blog/2018/08/21/this-week-in-rust-248/

> [disposition: merge] eRFC: if- and while-let-chains, take 2.

https://api.github.com/repos/rust-lang/rfcs/issues/2497

It's not convenient to read RFCs in JSON.

**Comment by nasa42** [comment]
Closed by https://github.com/cmr/this-week-in-rust/pull/696.
