### ISSUE TITLE
Reddit links

### ISSUE THREAD

**Issue by wycats** [cmr/this-week-in-rust#709]
I noticed that TWIR started directing people to Reddit to discuss various topics.

I personally try to avoid Reddit for Rust news, and I don't like being directed to Reddit in order to discuss topics of the week. I also believe that some of the people who write blog posts that appear in TWiR don't review Reddit and would find it frustrating that TWiR appears to direct people there to provide feedback.

I can understand the motivation for this change, but I wanted to register that I would personally prefer not to continue directing readers of TWiR to conversations on Reddit.

**Comment by nasa42** [comment]
I agree with the sentiment here and Reddit links are no longer present in this week's issue. I've made the public announcement [here](https://www.reddit.com/r/rust/comments/9d3sjf/this_week_in_rust_250/e5f75jh/).

**Comment by zealousidealroll** [comment]
As a Reddit user, I agree with this decision. Partially, because blog authors might have other preferred discussion points, but mostly because when the discussion link is at the bottom it'll encourage people to read the blog post before commenting on it.

**Comment by bestouff** [comment]
How about linking with just icons ? Less intrusive, and you can stack a few for reddit, HN, the forum, etc.
