### ISSUE TITLE
Typo in TWiR 276

### ISSUE THREAD

**Issue by martin-t** [cmr/this-week-in-rust#848]
It seems a stray "15" got into the second quote in the [latest](https://github.com/cmr/this-week-in-rust/blob/master/content/2019-03-05-this-week-in-rust.md#quote-of-the-week) TWiR.

**Comment by nasa42** [comment]
Thanks. 15 is probably the link count from https://users.rust-lang.org/t/twir-quote-of-the-week/328/626.
