### ISSUE TITLE
This week in rust 277 - Dead telegram meeting link

### ISSUE THREAD

**Issue by senden9** [cmr/this-week-in-rust#862]
Hi!

The link "[Mar 27. Rust Events Team Meeting on Telegram.](https://t.me/joinchat/EkKINhHCgZ9llzvPidOssA)" is dead. Telegram tells "This invite link is invalid or has expired".

**Comment by nasa42** [comment]
Thanks for reporting this. I'll skip the Telegram link in future issues.
