### ISSUE TITLE
Add rust-malaysia hello world post?

### ISSUE THREAD

**Issue by pickfire** [cmr/this-week-in-rust#872]
Not sure if this is appropriate to be brought up to TWIR. Here's Rust Malaysia first post.

https://rust-malaysia.github.io/community/2019/03/11/hello-world.html

If any improvements can be made, feel free to suggest.

**Comment by nasa42** [comment]
Thanks for the PR!

To direct TWiR's focus on technical articles (and important community news), we usually avoid including getting-started-with-Rust articles. We had a lot of these in past, and it is unlikely that any new information can be extracted from new articles on these topics.

If you have an upcoming event on Rust, please create a new issue and we'll be happy to list it!

**Comment by pickfire** [comment]
@nasa42 I do have new events but I have already added to rust calendar.

**Comment by nasa42** [comment]
I'll fetch it from there, thanks!

**Comment by pickfire** [comment]
@nasa42 I did add the event to the rust calendar but why does it not show up in the post? The event is on 2019 May 8th titled "Rust Malaysia Meetup Kuala Lumpur"?

**Comment by nasa42** [comment]
We list events for next 14 days (with some exception for major conferences). We'll be listing it upcoming weeks. :+1:
