### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by asaaki** [cmr/this-week-in-rust#880]
<img width="941" alt="Screenshot 2019-04-03 12 06 49" src="https://user-images.githubusercontent.com/446613/55470993-12b42100-5609-11e9-8e4f-760feec365ba.png">

The SSL/TLS certificate expired this morning.
I guess there is no auto-updating system in place?

**Comment by vincentdephily** [comment]
Incidentally, setting `HTTP Strict Transport Security` might be overkill for a domain that doesn't have a login and has only static/generated content (unless I'm wrong on one of those points) ? I'm all for TLS everywhere, but I could tolerate reading my Rust news unencrypted every now and then ;)

**Comment by pietroalbini** [comment]
ping @nasa42 @llogiq

**Comment by nasa42** [comment]
I've emailed @cmr who manages the server. I assume he is in Pacific time zone and should come online shortly.

**Comment by nasa42** [comment]
We're back online. We plan to migrate to GitHub pages this weekend so this shouldn't happen again in future.
