### ISSUE TITLE
pull in updates from more rust components

### ISSUE THREAD

**Issue by gnzlbg** [cmr/this-week-in-rust#896]
* `core::arch` lives in `rust-lang-nursery/stdsimd`
* libc lives in `rust-lang/libc`

**Comment by nasa42** [comment]
I'd include @llogiq for his feedback, but I think it would be extra effort to extract changes from all different repositories and it's likely that for now we'll stick to the `rust-lang/rust` repo (I believe we also include `rust-lang/cargo` for major changes).

Thanks for your suggestion!
