### ISSUE TITLE
Call for participation: Running a Rust Belt RustBridge

### ISSUE THREAD

**Issue by carols10cents** [cmr/this-week-in-rust#918]
Hi, I just posted [this announcement](https://users.rust-lang.org/t/rust-belt-rustbridges/28332) wherein I'm looking for people to run RustBridge workshops this summer. I'd love if this could make it in next week's issue under the "call for participation" section! Thank you! ❤️

**Comment by nasa42** [comment]
Added to today's issue. Thanks for the tip!
