### ISSUE TITLE
Call for participation: segfault in minix_oxide

### ISSUE THREAD

**Issue by Shnatsel** [cmr/this-week-in-rust#937]
miniz_oxide is the pure Rust backend for flate2, the most popular Rust compression/decompression crate. It is now faster on decompression than the default C backend, and is the only option for WASM.

Despite its popularity, they have a memory safety issue in "help wanted" state for ages: https://github.com/Frommi/miniz_oxide/issues/14
It would be great to include it in the TWIR "Call for participation" section.

**Comment by nasa42** [comment]
It will be added in this week's issue. Thanks!
