### ISSUE TITLE
Publicize Rustexp somehow?

### ISSUE THREAD

**Issue by carols10cents** [cmr/this-week-in-rust#939]
Can [Rustexp](https://rustexp.lpil.uk/), this online Rust regular expression editor and tester, be publicized? It's not quite "crate of the week", but if you don't have one anyway, maybe bend the rules a bit? I needed this the other day and didn't know it existed, so I think more people should know about it :)

oh it's by lpil but I don't want to ruin the surprise by tagging them

**Comment by nasa42** [comment]
I added the suggestion here: https://users.rust-lang.org/t/crate-of-the-week/2704/575
It should be listed for CotW for next week! :crossed_fingers:
