### ISSUE TITLE
Call for participation: crash in libgoblin

### ISSUE THREAD

**Issue by Shnatsel** [cmr/this-week-in-rust#947]
`goblin` is a one-stop shop crate for parsing binary formats like ELF, PE and Mach-O. It has a number of high-profile dependents.

There is an issue where it crashes the process on some inputs that's been in "help wanted" state for months: https://github.com/m4b/goblin/issues/120

It would be great to include it in the TWIR "Call for participation" section.

**Comment by nasa42** [comment]
This will be included in today's issue. :+1:
