### ISSUE TITLE
Consider using GitHub Releases

### ISSUE THREAD

**Issue by TomasHubelbauer** [cmr/this-week-in-rust#958]
Hey there, I'd like to suggest GitHub Releases be cut each time new TWIR goes live so that people can watch this repo using Watch Releases. Regular watch is too noisy for me and I'm sure (at least some) others so I prefer to watch releases whenever I can. Hope this makes sense! Thank you.

**Comment by nasa42** [comment]
Thanks for your suggestions.
It adds one extra step to TWiR weekly release process but I'm unsure about its usefulness. You can also follow our [Atom](https://this-week-in-rust.org/atom.xml), [RSS](https://this-week-in-rust.org/rss.xml), [Twitter](https://twitter.com/ThisWeekInRust) feeds, or subscribe to the [newsletter](https://this-week-in-rust.org/) to be notified of changes.
