### ISSUE TITLE
Subscribe button does not work?

### ISSUE THREAD

**Issue by lastorset** [cmr/this-week-in-rust#96]
I tried to sign up for e-mail, but I don't think it worked. I didn't get any feedback when I clicked or any confirmation e-mails. Furthermore, a caret appeared in the button, and on inspection it seems to be a text field, not `<input type="submit">` (and not part of a `<form>` either). I suspect there's supposed to be some JS doing some magic here, but my browsers (Opera and Firefox) don't load anything.

This is the affected URL:
http://this-week-in-rust.org/staging/blog/2015/07/27/this-week-in-rust-89/

**Comment by nasa42** [comment]
This should be fixed in latest builds.

**Comment by nasa42** [comment]
Please create a new issue if you still think this is a problem for you. Closing this.

**Comment by lastorset** [comment]
It works for me, thanks!

man. 12. okt. 2015, 20.09 skrev Vikrant Chaudhary <notifications@github.com
