### ISSUE TITLE
Ability to browse next and previous issues

### ISSUE THREAD

**Issue by RussianCow** [cmr/this-week-in-rust#986]
It would be great to have links to the next and previous (if applicable) issues on the article page. I just discovered this newsletter (which is great by the way!), but there is currently no way for me to continue browsing once I go to an article page without going back to the archive page.

I can submit a PR if that would be helpful. :)

Thank you for spending your time on this!

**Comment by nasa42** [comment]
I'll be happy to review a PR for this!

**Comment by RussianCow** [comment]
Sounds great! I'll work on it this week when I have time.
